### ISSUE TITLE
Could not resolve xerces:xercesImpl:2.11.0.beta. Received status code 409 from server: Conflict

### ISSUE THREAD

**Issue by bestta** [interactive-instruments/etf-webapp#103]
During the compilation of etf-webapp from Windows-DOS I obtained the following message:

:compileJava FAILED
FAILURE: Build failed with an exception.

What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
Could not find de.interactive_instruments:ii-commons-util:2.0.0-SNAPSHOT.
Searched in the following locations:
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
https://repo1.maven.org/maven2/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
https://repo1.maven.org/maven2/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
https://repo1.maven.org/maven2/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
http://files.basex.org/maven/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
http://files.basex.org/maven/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
http://files.basex.org/maven/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/ii-commons-util/2.0.0-SNAPSHOT/ii-commons-util-2.0.0-SNAPSHOT.jar
Required by:
project :
Could not find de.interactive_instruments.etf:etf-core:1.0.0-SNAPSHOT.
Searched in the following locations:
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
http://files.basex.org/maven/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
http://files.basex.org/maven/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
http://files.basex.org/maven/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-core/1.0.0-SNAPSHOT/etf-core-1.0.0-SNAPSHOT.jar
Required by:
project :
Could not find de.interactive_instruments.etf:etf-spi:1.0.0-SNAPSHOT.
Searched in the following locations:
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
http://files.basex.org/maven/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
http://files.basex.org/maven/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
http://files.basex.org/maven/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-spi/1.0.0-SNAPSHOT/etf-spi-1.0.0-SNAPSHOT.jar
Required by:
project :
Could not find de.interactive_instruments.etf:etf-bsxds:2.0.0-SNAPSHOT.
Searched in the following locations:
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
http://files.basex.org/maven/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
http://files.basex.org/maven/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
http://files.basex.org/maven/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-bsxds/2.0.0-SNAPSHOT/etf-bsxds-2.0.0-SNAPSHOT.jar
Required by:
project :
Could not find de.interactive_instruments.etf:etf-rc:1.0.0-SNAPSHOT.
Searched in the following locations:
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-releases-local/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
http://services.interactive-instruments.de/etfdev-af/ext-cache/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
https://repo1.maven.org/maven2/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
file:/C:/Users/struzel/.m2/repository/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
http://files.basex.org/maven/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
http://files.basex.org/maven/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
http://files.basex.org/maven/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/maven-metadata.xml
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.pom
https://services.interactive-instruments.de/etfdev-af/ext-deegree-cache/de/interactive_instruments/etf/etf-rc/1.0.0-SNAPSHOT/etf-rc-1.0.0-SNAPSHOT.jar
Required by:
project :
Could not resolve xerces:xercesImpl:2.11.0.beta.
Required by:
project :
Could not resolve xerces:xercesImpl:2.11.0.beta.
> Could not get resource 'https://services.interactive-instruments.de/etfdev-af/snapshot/xerces/xercesImpl/2.11.0.beta/xercesImpl-2.11.0.beta.pom'.
> Could not GET 'https://services.interactive-instruments.de/etfdev-af/snapshot/xerces/xercesImpl/2.11.0.beta/xercesImpl-2.11.0.beta.pom'. Received status code 409 from server: Conflict

I checked and the manual download fails too. Is the jar-file corrupt or not accessible?
Notice that I added in my maven settings.xml the proxy settings and I passed them as arguments in **gradlew build war** command.

**Operating systems and browser**
Windows 10 64bit
jdk1.8.0_121

**Steps to Reproduce**
go to the root dir of the src code
execute the command: ./gradlew build war
The build fails with the above message.

**Comment by jonherrmann** [comment]
The documentation is currently being revised and building the application is not documented yet. Currently, the user, installation and API manual has a higher priority than the developer documentation.

**Comment by jonherrmann** [comment]
https://github.com/interactive-instruments/etf-webapp/blob/master/docs/Developer_manuals/Building.adoc

**Comment by jonherrmann** [comment]
HTML doc is now available here: http://docs.etf-validator.net/Developer_manuals/Building.html
