### ISSUE TITLE
Loading etf-webapp.war with Tomcat, package functx-1.0.xar is required

### ISSUE THREAD

**Issue by elisabettastruzzi** [interactive-instruments/etf-webapp#105]
After having copied the etf-webapp.war to  TOMCAT_INSTALLATION_DIRECTORY\webapps, as described in the [User manual](http://docs.etf-validator.net/Admin_manuals/index.html#ETF-config-file), and started catalina, an exception is retrieved:
`Caused by: de.interactive_instruments.exceptions.InitializationException: FunctX XQuery Function Library installation failed. Download functx-1.0.xar manually and copy it to the BaseXRepo folder [bxerr:BXRE0001] Package 'http://files.basex.org/modules/expath/functx-1.0.xar' does not exist.
at de.interactive_instruments.etf.dal.dao.basex.BsxDataStorage.initBsxDatabase(BsxDataStorage.java:396)
at de.interactive_instruments.etf.dal.dao.basex.BsxDataStorage.init(BsxDataStorage.java:241)
at de.interactive_instruments.etf.webapp.controller.DataStorageService.init(DataStorageService.java:58)`
The complete log is here: [etf.log.txt](https://github.com/interactive-instruments/etf-webapp/files/978537/etf.log.txt)

Do I have to install BaseX and, after that operation, execute manually REPO INSTALL http://files.basex.org/modules/expath/functx-1.0.xar?

Operating systems and browser
Windows 10 64bit
jdk1.8.0_121

Steps to Reproduce
copy etf-webapp.war to TOMCAT_INSTALLATION_DIRECTORY\webapps
startup Tomcat
The webapp context initialization fails with the above message.

**Comment by jonherrmann** [comment]
Do you have an idea why the download fails?
Are you using a proxy server and have you set the JVM parameter http.proxyHost? 

Download the functx-1.0.xar file, extract it (the xar is a zip file), rename the functx-1.0 directory to http-www.functx.com-1.0 and copy it to:
E:\struzel\etf\ds\db\repo

We will add the information to the error message.

The application has not been tested with proxy servers, and even if the functx installation works, other functionality will most likely not work after startup, especially service tests.

**Comment by elisabettastruzzi** [comment]
Thanks for the suggestions. It runs now.
