### ISSUE TITLE
class TimeUtils error: cannot find symbol calcDelay

### ISSUE THREAD

**Issue by elisabettastruzzi** [interactive-instruments/etf-webapp#116]
During the build of the etf-webapp, the following compilation error is generated:

`17:46:09.620 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
17:46:09.879 [ERROR] [system.err] E:\struzel\GP-VALIDATOR\etf-webapp\src\main\java\de\interactive_instruments\etf\webapp\controller\TestObjectController.java:226: error: cannot find symbol
17:46:09.879 [ERROR] [system.err]                                       TimeUnit.SECONDS.toMillis(TimeUtils.calcDelay(0,9,0)),
17:46:09.879 [ERROR] [system.err]                                                                          ^
17:46:09.879 [ERROR] [system.err]   symbol:   method calcDelay(int,int,int)
17:46:09.879 [ERROR] [system.err]   location: class TimeUtils
17:46:09.928 [ERROR] [system.err] E:\struzel\GP-VALIDATOR\etf-webapp\src\main\java\de\interactive_instruments\etf\webapp\controller\TestResultController.java:200: error: cannot find symbol
17:46:09.928 [ERROR] [system.err]                                       TimeUnit.SECONDS.toMillis(TimeUtils.calcDelay(0,9,0)),
17:46:09.928 [ERROR] [system.err]                                                                          ^
17:46:09.928 [ERROR] [system.err]   symbol:   method calcDelay(int,int,int)
17:46:09.928 [ERROR] [system.err]   location: class TimeUtils
17:46:09.990 [ERROR] [system.err] Note: E:\struzel\GP-VALIDATOR\etf-webapp\src\main\java\de\interactive_instruments\etf\webapp\controller\EtfConfigController.java uses or overrides a deprecated API.
17:46:09.991 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
17:46:09.991 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
17:46:09.991 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
17:46:09.991 [ERROR] [system.err] 2 errors
`

Consider that the TimeUtils class is not explicitly  imported in the TestResultController class. The etf-webapp.war artifact creation fails.

**Comment by jonherrmann** [comment]
Forgot to push the function to GitHub. Fixed now
