### ISSUE TITLE
Windows: illegal char in path

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-webapp#118]
Reported by @elisabettastruzzi:

`de.interactive_instruments.etf.testdriver.ExecutableTestSuiteUnavailable: Executable Test Suite "'Conformance Class: Download Service - Direct WFS (EID: ed2d3501-d700-4ff9-b9bf-070dece8ddbd, V: 0.1.0 )'" is not available: C:\ProgramData\etf\projects\ets-repository\service\ds-wfs-direct-soapui-project.xml Illegal char <:> at index 54: xxx\temp\Conformance Class: Download Service - Direct WFS_ets_9169773634231963175etf`

**Comment by jonherrmann** [comment]
[etf-suitd-2.0.0.jar](https://services.interactive-instruments.de/etfdev-af/snapshot/de/interactive_instruments/etf/testdriver/etf-suitd/2.0.0-SNAPSHOT/etf-suitd-2.0.0-20170716.203428-9.jar) test driver must be redeployed to the test driver directory

**Comment by elisabettastruzzi** [comment]
Redeployed. It works, now.
Thanks.
