### ISSUE TITLE
An exception occurred while trying to invoke "http://localhost:8080/etf-webapp/v2/TestObjects"

### ISSUE THREAD

**Issue by OscarD31** [interactive-instruments/etf-webapp#127]
### Description

I have deployed the validator in my system. But every time I upload a file, I get an error.

The log file shows the following error:

**ERROR d.i.e.w.d.ApiError - EXID-1504091152412: An exception occurred while trying to invoke "http://localhost:8080/etf-webapp/v2/TestObjects"**

To install the validator, I have followed these steps: http://docs.etf-validator.net/Admin_manuals/index.html

I'm using the INSPIRE test suites.

### Operating systems and browser

- Windows 7 64-bits
- Java 1.8
- Tomcat 8
- Chrome browser

I have attached the log:

[etf.zip](https://github.com/interactive-instruments/etf-webapp/files/1263373/etf.zip)

**Comment by jonherrmann** [comment]
Thanks @OscarD31  for the detailed issue report.

Is an error message shown in the web interface?

Does your system have enough resources ( 4 GB RAM) and have you configured your Java heap size to use it (see [JVM -Xmx parameter](https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html))?

Can you please post the JSON output of http://localhost:8080/etf-webapp/v2/status

**Comment by OscarD31** [comment]
I'm feeling like an idiot now. I installed the validator in the wrong computer.

It doesn't have enough resources:

_{"name":"ETF","status":"MAJOR","heartbeat":"1504096639330","willExpireAt":"1504096679330","version":"2.0.0-b170817T1316","allocatedMemory":"186817744","presumableFreeMemory":"72704816","totalSpace":"37472956416","freeSpace":"3391406080","cpuLoad":"0,000000","messages":["Less then 5 GB disk space available","Less then 13% disk space available","Less then 512 MB RAM available"]}_

I will install it in the correct computer. I'll let you know if the problem is resolved that way.

Thanks!

**Comment by OscarD31** [comment]
The validator is working as expected in the good computer.

Sorry!

**Comment by jonherrmann** [comment]
Glad to hear it is working now.

We will think about how we can inform in the web interface, that something is not configured correctly or the system has not enough resources to work properly.

Thanks for the feedback.
