### ISSUE TITLE
Browser blocks mixed content - link to external content over https

### ISSUE THREAD

**Issue by stijngoedertier** [interactive-instruments/etf-webapp#132]
When accessing etf-webapp through an HTTPS proxy, browsers like FireFox and Chrome do not correctly display the start page (due to "mixed content blocking") see this [screenshot:  etf-webapp-mixed-content-error](https://user-images.githubusercontent.com/1309223/30422051-0af2a988-993f-11e7-8673-dca954fd0f23.png). When disabling this security check in the browser, the pages are displayed correctly.

This problem would probably be solved by only linking to external CSS content over https. I see for instance the following line in the main HTML page:

```
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css" />
```

**Comment by jonherrmann** [comment]
Thanks Stijn!
