### ISSUE TITLE
TEAM Engine 5.0 released with changes to the REST API

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/etf-webapp#135]
See http://lists.opengeospatial.org/pipermail/cite-forum/2017-October/001702.html

This will affect the access to the OGC CITE tests once the OGC CITE production environment will be updated to version 5.0.

**Comment by jonherrmann** [comment]
Current version works with http://cite.opengeospatial.org/te2/rest/suites/wfs20/1.27/
