### ISSUE TITLE
Test Suites are not loaded 

### ISSUE THREAD

**Issue by OscarD31** [interactive-instruments/etf-webapp#136]
Good evening!

I think my problem is related with the WebApp and not with the INSPIRE Test Suites, but if I'm wrong, sorry.

In my computer, I deployed the webapp (2.0.0 release candidate) and the tests without any issue.

The other day, I tried to deploy the validator in another computer following the same steps. But, for some reason, only 1 Executable test Suite is loaded:

![testetf](https://user-images.githubusercontent.com/30283946/31445803-2c0164e6-ae9f-11e7-87bc-6db38d6926d9.png)

This is what the log says:

> 2017-10-10 13:01:26.348 [localhost-startStop-1] INFO  d.i.e.w.c.TestDriverController - Loaded Test Driver TEAM Engine test driver - 1.0.0-SNAPSHOT (07f42606-41b1-4871-a83b-64c20012f03b)
**2017-10-10 13:01:26.442 [localhost-startStop-1] INFO  d.i.e.w.c.TestDriverController - 1 Executable Test Suites loaded**
2017-10-10 13:01:26.442 [localhost-startStop-1] INFO  d.i.e.w.c.EtsController - Executable Test Suite controller initialized!

The only error I see in the log is this one:

> 2017-10-10 13:01:20.773 [localhost-startStop-1] INFO  d.i.e.t.TestDriverLoader - Loading test driver "4dddc9e2-1b21-40b7-af70-6a2d156ad130"
2017-10-10 13:01:20.773 [localhost-startStop-1] INFO  d.i.e.t.ComponentContainer - Preparing Test Driver BaseX test driver 2.0.0-SNAPSHOT 
2017-10-10 13:01:24.598 [localhost-startStop-1] INFO  d.i.e.t.TypeBuildingFileVisitor - Extracting packaged types to gradle-wrapper
2017-10-10 13:01:24.630 [localhost-startStop-1] ERROR d.i.e.t.TypeBuildingFileVisitor - Failed to resolve dependency 
de.interactive_instruments.etf.testdriver.DependencyResolutionException: Referenced Object with ID 54d5f755-e20c-40a7-ab72-5600c71dd049, defined in C:\ProgramData\etf\projects\data-gn\gn-gml\ets-gn-gml-bsxets.xml not found!

The main difference with the deployment that is working is the access URL. In the new one, localhost is not used and the port is differente, too. But I have followed the instructions in the guide to change the configuration in those cases.

I've called http://myWeb:9080/etf-webapp/v2/status to see if there was any issue, but everything is OK.

Is there anything that I'm missing?

System:

Windows Server 2016
5GB RAM
Apache Tomcat 8.5

Thanks!

**Comment by jonherrmann** [comment]
Hi Oscar,
please try to install the [latest version](https://github.com/interactive-instruments/etf-webapp/releases/tag/2.0.0-rc.2) (updated today). You should also update the executable test suites from the [ets repository](https://github.com/inspire-eu-validation/ets-repository/archive/master.zip).

Please let us know if this fixes the problem.

**Comment by OscarD31** [comment]
Hi.

I haven't forgotten about this. I will let you know as soon as I have access to the machine where it must be deployed.

**Comment by jonherrmann** [comment]
Feel free to reopen the issue if the problem persists
