### ISSUE TITLE
Documentation for  /v2/TestRuns/{id}/progress

### ISSUE THREAD

**Issue by heidivanparys** [interactive-instruments/etf-webapp#137]
Would it be possible to provide more documentation about this method and how to use parameter "pos" and the "val" and "max" from the response?

The documentation says "the number of executed and remaining Test Steps", how does this relate to "val" and "max"?

It seems that the following logic works:
```
boolean isFinished = val < max ? false : true;
```

**Comment by cportele** [comment]
That is correct. If you click on "Model" (instead of "Example Value") you will see:

```
log (Array[string], optional): Log messages ,
max (string, optional): Maximum number of Test Steps ,
val (string, optional): Completed Test Steps
```

`max` is the total number of test steps in all the test suites of the test run and `val` is the number of those test steps that have been completed. Do you have any recommendations of what should be added to the documentation?

**Comment by heidivanparys** [comment]
Ok, I didn't notice the "Model" links until now, I only looked at the example values so far, the documentation there is helpful of course.

I would suggest the following in the Implementation Notes:
"Retrieve one Test Run status including log messages, the maximum number of Test Steps and the number of already executed TestSteps at the time of the request".

![image](https://user-images.githubusercontent.com/11427611/31886100-2d8477b0-b7f3-11e7-95ff-b602bb8296a5.png)

How is the maximum number of test steps calculated? Because it seems that this value is not necessarily a constant in the course of one test run:

![image](https://user-images.githubusercontent.com/11427611/31886186-9995d174-b7f3-11e7-9fda-70234b6bb336.png)

[etfclient.log](https://github.com/interactive-instruments/etf-webapp/files/1406843/etfclient.log)
[etf-webapp.log](https://github.com/interactive-instruments/etf-webapp/files/1406844/etf-webapp.log)

**Comment by cportele** [comment]
Thanks, Heidi. @jonherrmann, can you have a look? Probably we should rather say "estimated total number of Test Steps".

Regarding the increasing number of test steps: In service tests this is normal. For example, you know how many feature types you have to test only after you have analysed the capabilities. Additional test steps are created for testing each feature type.
