### ISSUE TITLE
API call error

### ISSUE THREAD

**Issue by OscarD31** [interactive-instruments/etf-webapp#140]
Good morning!

Every time I try to start a test I get the following error:

> API call error: The test run initialization failed due to an internal error. Please contact a system administrator.

Is this a known issue? Or am I the only one?

Thanks!

**Comment by cportele** [comment]
Is this in your local installation or a public one?

**Comment by OscarD31** [comment]
Sorry. I forgot.

It's the public one: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/

**Comment by cportele** [comment]
I will forward this to JRC, but close it here as it is specific to the deployment at JRC.
