### ISSUE TITLE
[webapi-v2-beta] INSPIRE validator ETF API  does not work 

### ISSUE THREAD

**Issue by klimeto** [interactive-instruments/etf-webapp#145]
Dear devs,
I have noticed weird behavior of etf api lately. First its been unavailable for same period, mostly reporting with status value major and now it does not work at all. 

Here is the log: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/5da93346-37bd-4aa1-8f42-3683f8e9c2a4/log

Here is a blank report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID5da93346-37bd-4aa1-8f42-3683f8e9c2a4.html

Here is the tested resource: http://klimeto.com/projects/2017/mzp/apps/testovanie_inspire_zdrojov/data/xml/GetRecordByIdResponse.xml

Could you help please?
What is the roadmap for more stable release?
We have developed a testing app which fully rely on etf api and would like to release it for the data providers in order to easy their work in implementing INSPIRE on national level.

Thanks for understanding,
Tomas

**Comment by robsgnao** [comment]
Dear Tomas,
we will be back to you soon with a reply.

Regards,

Roberto

**Comment by klimeto** [comment]
Dear Roberto,

The ETF API ran again out of resources and reports status: MAJOR.

See here please: http://klimeto.com/projects/2017/mzp/apps/testovanie_inspire_zdrojov/api/indexETF.php

name: INSPIRE Validator

status: MAJOR

heartbeat: 1513432786770

willExpireAt: 1513432826770

version: 2.0.0-b171211T1709

uptime: 57490

allocatedMemory: 608651840

presumableFreeMemory: 5798933952

totalSpace: 107223191552

freeSpace: 5304233984

cpuLoad: 0.000375

messages: Less then 5 GB disk space available,Less then 13% disk space available

Is there any progress in making the JRC instance ETF API more stable?

Thank you,
Tomas

**Comment by robsgnao** [comment]
Dear Tomas,
it is fixed now, please remember that this instance of the Validator is not production grade, the service is offered within the INSPIRE Sandbox (see disclaimer at http://inspire-sandbox.jrc.ec.europa.eu/).
For production grade services, for the time being, please use the Validator instance included in the INSPIRE Geoportal (http://inspire-geoportal.ec.europa.eu/validator2/).

Thanks,

Roberto
