### ISSUE TITLE
The use of SoapUI v5.3.0 as a development tool for ETS not available

### ISSUE THREAD

**Issue by PaulaRodrigo-Geograma** [interactive-instruments/etf-webapp#148]
**Please note:

This repository is intended for issue reports specific to the ETF validator.
If you have an issue with an Executable Test Suite, then please use the
corresponding repository, for instance the [INSPIRE ETS repository](https://github.com/inspire-eu-validation/ets-repository)
if you have an issue with an INSPIRE test.

Our User, Administrator and Developer
manuals are available here: http://docs.etf-validator.net/.**

### Prerequisites for a bug report

* [x] Set a clear and descriptive title
* [x] Can you reproduce the problem
* [x] Did you [use the Github issue search](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Ainteractive-instruments) to check whether your bug has already been reported?
* [x] Upload excerpts of the etf.log, catalina.out/log and localhost-<date>.log files. Important parts are:
the initialization log entries beginning with the ETF ASCII logo and ending with "TestRunController initialized!" plus the last exception messages.
* [x] If the problem is related to the Web user interface: include screenshots
* [x] If the problem is related to specific test data, provide the URL of your
service / the file you have uploaded or referenced.
If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be fixed for services/datasets that we cannot
access.
* [x] Don't forget to remove sensitive information from uploaded files!!!

### Description

The ETS development environment for services (Download Services 3.1) is based on SoapUI v5.3.0 & Plugins developed by the current ETF. 
The problem is that SoapUI v5.3.0 is no longer available and the current SoapUI v5.4.0 does not work with the current plugins as they are not ready to work on SoapUI v5.4.0. 
It is not possible to install this development environment to test the Services Executable Tests.

Had this problem been detected to date?

### Operating systems and browser

- Developing Executable Test Suites Manual:
http://docs.etf-validator.net/v2.0/Developer_manuals/Developing_Executable_Test_Suites.html

- Reference 4. SoapUI based Test Suites:
http://docs.etf-validator.net/v2.0/Developer_manuals/Developing_Executable_Test_Suites.html#_soapui_based_test_suites

### Steps to Reproduce

[Describe the exact steps which can be used to reproduce the problem]

1. Install SoapUI 5.3.0 installed --> version not available
Actual behavior: Install SoapUI 5.4.0

2. Download this ZIP file (using "etf-public-dev" as username and password), extract the ZIP file in any directory and run 'install-plugins.bat'

"SoapUI 5.3.0 is not installed!
Please download the Open Source 5.3.0 version of SoapUI from https://www.soapui.org/downloads/soapui.html and install it."

**Actual behavior:** [Describe the behavior you observed after following the steps]

**Comment by jonherrmann** [comment]
It looks like smartbear has simply removed SoapUI 5.3.0 as it is not listed in the previous download section: https://www.soapui.org/downloads/soapui/soapui-os-older-versions.html

Other links like, http://smartbearsoftware.com/distrib/soapui/5.3.0/SoapUI-x64-5.3.0.exe or https://s3.amazonaws.com/downloads.eviware/soapuios/5.3.0/SoapUI-x64-5.3.0.exe are also not working.

As a workaround you could try to use version 5.4.0 and replace line 7 in the startup script:
```
 SET REQUIRED_SOAPUI_VERSION=5.3.0
```
with
```
 SET REQUIRED_SOAPUI_VERSION=5.4.0
```

If the plugin does not work with version 5.4 and version 5.3 is not made available again in the future, we would need to upgrade the SoapUI testdriver and the plugin.

**Comment by PaulaRodrigo-Geograma** [comment]
I have tried several times to install SoapUI 5.3.0 available on some websites, like the ones you indicate, and an installation error occurs.
Specifically, it refers to the main () class of the code, but does not indicate anything else.

Previously I also did the test of modifying the file by directly replaying the version in line 7 of the plugin's start script:
SET REQUIRED_SOAPUI_VERSION = 5.3.0
with
SET REQUIRED_SOAPUI_VERSION = 5.4.0

The result does not work.
Keep indicating the same error, this time with the new version number:

"SoapUI 5.4.0 is not installed!
Please download the Open Source 5.4.0 version of SoapUI from https://www.soapui.org/downloads/soapui.html and install it."

And this version if I have it installed at the moment, but the installer of the ETF plugin does not recognize it.

**Comment by jonherrmann** [comment]
What is your installation path of SoapUI?

If neither

```
%PROGRAMFILES(x86)%\Smartbear\SoapUI-5.4.0\bin
```
nor
```
%ProgramFiles%\Smartbear\SoapUI-5.4.0\bin\
```
are found, you need to set the variable `CUSTOM_SOAPUI_HOME` .

**Comment by PaulaRodrigo-Geograma** [comment]
I had to use the variable CUSTOM_SOAPUI_HOME, because my installation path was:

C: \ Program Files \ SmartBear \ SoapUI-5.4.0 \ hermesJMS \ bin

The 5.4.0 installer by default loads the JMS Messages extension causing the original installation path to be altered.

Adding this variable and modifying the reference to the version of line 7, is solved.
thanks!

**Comment by PaulaRodrigo-Geograma** [comment]
The changes that you proposed to me to do on the installation file and the plugin packages give good results. You can now run the ETF test on the SOAP ui program.

Even so, I think there should be a new compiled version of these plugins and document and inform the public about the problem they are going to encounter with these obsolete versions.

Thank you very much for the help

**Comment by jonherrmann** [comment]
Thanks, I have opened a new issue here https://github.com/interactive-instruments/etf-webapp/issues/153 and will close this one.
