### ISSUE TITLE
Docker problems

### ISSUE THREAD

**Issue by larsnaesbye** [interactive-instruments/etf-webapp#150]
I am trying to implement the ETF validator webapp within Docker, and I've run into some problems. 

The problem is that when I run it as Docker image I can make it work fine in one environment but not the other. I use the command

sudo docker run --name etf -d -p 8082:8080 -v ~/etf:/etf iide/etf-webapp:latest (we access etf-webapp on port 8082 through HAproxy)

 
This pulls the app fine from the docker image hub and runs it. It runs correctly in our test environment but not in production, and in production I get a different error when accessing the top level (one level up from /etf-webapp ).

In test, I get :
 

```
No context on this server matched or handled this request.

Contexts known to this server are:

/etf-webapp ---> o.e.j.w.WebAppContext@4520ebad{/etf-webapp,[file:///tmp/jetty/jetty-0.0.0.0-8080-etf-webapp.war-_etf-webapp-any-6061467880627406135.dir/webapp/, jar:file:///tmp/jetty/jetty-0.0.0.0-8080-etf-webapp.war-_etf-webapp-any-6061467880627406135.dir/webapp/WEB-INF/lib/springfox-swagger-ui-2.6.1.jar!/META-INF/resources],AVAILABLE}{/etf-webapp.war}
```

And in production:

```
No context on this server matched or handled this request.

Contexts known to this server are:

/etf-webapp ---> o.e.j.w.WebAppContext@4520ebad{/etf-webapp,[file:///tmp/jetty/jetty-0.0.0.0-8080-etf-webapp.war-_etf-webapp-any-7995283481129842187.dir/webapp/, jar:file:///tmp/jetty/jetty-0.0.0.0-8080-etf-webapp.war-_etf-webapp-any-7995283481129842187.dir/webapp/WEB-INF/lib/springfox-swagger-ui-2.6.1.jar!/META-INF/resources],UNAVAILABLE}{/etf-webapp.war}
```
Note the difference between AVAILABLE and UNAVAILABLE.

Both servers run the same OS and are on the same subnet, and I get no errors during the Docker commands. One is virtual and one is physical but this I suppose makes no difference to Docker.

Do you have an idea what might be the cause for this difference? It would be a great help if you could point me in the right direction.

**Comment by jonherrmann** [comment]
Hi Lars,

are the image IDs identical in both environments (`sudo docker images iide/etf-webapp`) ?

Have you tried to update the container in the production env. (means `docker stop CONTAINER_ID`, `docker rm CONTAINER_ID` and `docker pull iide/etf-webapp`) ?

**Comment by larsnaesbye** [comment]
Hi Jon,

Yes, both give this result:

```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
docker.io/iide/etf-webapp   latest              03480e59a9e8        12 weeks ago        319.7 MB
```
Updating the container doesn't change it.

The production URL is : https://etfvalidator.kortforsyningen.dk/

**Comment by jonherrmann** [comment]
Could you please upload the docker logs output of the container, check if an etf.log file was created in the container and upload it as well?

Another thing that comes to my mind: there might be a rights issue with the ~/etf mount point or the data in the ~/etf mount point have been corrupted. It could help to delete this directory and then re-build the container from the image.

**Comment by larsnaesbye** [comment]
There is indeed a much larger etf.log file in the production environment. Attaching it here.
[etf.zip](https://github.com/interactive-instruments/etf-webapp/files/1946129/etf.zip)

**Comment by larsnaesbye** [comment]
This worked! Thank you very much, @jonherrmann !

**Comment by DeordD** [comment]
> I have opened a new issue for it here: https://github.com/interactive-instruments/etf-webapp/issues/152

This link is broken. 

The issue can be found here https://github.com/etf-validator/etf-webapp/issues/152
