### ISSUE TITLE
GmlGeox tests fail to run: no binding for namespace

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-webapp#16]
Using version 1.0.2 of etf-gmlgeox, the tests for geomety validation fail to run.

I'm using this (sample) test project: https://github.com/Geonovum/etf-test-projects-nl/tree/master/src/data/GML3.2%20SF2%20en%202D-Geometrie

Log details:
```
[14:48:04,968]  Compiling test script
[14:48:05,007]  Starting xquery tests
[14:48:05,008]  Features: 0.3 ms
[14:48:05,010]  Statistics: 0.96 ms
[14:48:05,060]  Test Other.Geometry.01: 49.9 ms
[14:48:05,153]  Handling unexpected exception in TestRunTask.3e25c398-5d6e-4c58-b649-b243d839ff2b
[14:48:05,153]  Changed state from INITIALIZED to RUNNING
[14:48:05,156]  Testrun failed with an error: Stopped at ., 4/31:
[bxerr:BASX0000] No binding for namespace prefix imgeo

Stack Trace:
- ., 58/60
- ., 37/19
- ., 488/24
[14:48:05,156]  Duration: 0sec
[14:48:05,156]  TestRun finished
[14:48:05,156]  Changed state from RUNNING to FAILED
[14:48:05,156]  Releasing resources
```

**Comment by thijsbrentjens** [comment]
Files used for testing:

[venray_IMGeo_fout_20131202_klein.xml.txt](https://github.com/interactive-instruments/etf-webapp/files/248761/venray_IMGeo_fout_20131202_klein.xml.txt)

**Comment by cportele** [comment]
Hi @thijsbrentjens, I had this issue last week, too, on my machine under OS X (Mac). When I use Windows 7 this does not occur. We had not yet investigated this further (as using Windows works as a temporary fix). 

Under the Linux install that we have been using to deploy ETF this issue also does not show.

What environment are you using where the error occurs?

**Comment by thijsbrentjens** [comment]
it's a Linux environment:

CentOS release 6.6 (Final)
Tomcat 8
Java 1.8

**Comment by thijsbrentjens** [comment]
The test project itself is not final yet, but the geometry validation worked last week. I could try to return to the gmlgeox version of last week.

**Comment by jonherrmann** [comment]
I'am not sure if this is the class loading bug.

@thijsbrentjens can you try the following (replace variables ETF_DIR and the name of the etf-gmlgeox.jar file): 

# Download etf-gmlgeox.jar file

mkdir -p "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/
mv /tmp/etf-gmlgeox.jar  "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/

# workaround (Classloader fails to load dom4j)
unzip "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/etf-gmlgeox.jar  -d "$ETF_DIR"/td/bsx/lib

# workaround (Classloader fails to load Regex Util matches function )
 cp "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/etf-gmlgeox.jar  -d "$ETF_DIR"/td/bsx/lib

**Comment by cportele** [comment]
Out of curiosity, I used the test project and the venray file in my Windows BaseX environment and I get no errors (as expected).

[result.xml.txt](https://github.com/interactive-instruments/etf-webapp/files/248795/result.xml.txt)

**Comment by thijsbrentjens** [comment]
hi @jonherrmann , thanks for the info. There was a dir  "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/ already on our system. Including a GmlGeoX.jar.
I moved that one and put the 1.0.2 version in there.

Then (for my environment):
```unzip "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/etf-gmlgeox.jar -d "$ETF_DIR"/td/bsx/lib```

Restarted Tomcat, retested and got an exception:

```
Caused by: org.basex.query.QueryException: Class not found: 'de.interactive_instruments.etf.bsxm.GmlGeoX'.
	at org.basex.query.util.Err.get(Err.java:1212)
```

Then I did the last step you mentioned, restarted Tomcat and repeated the test. Now the class not found exception is gone, but the namespace issue is still there. From Tomcat's logging:

```
org.basex.query.QueryException: Stopped at ., 4/31:
[bxerr:BASX0000] No binding for namespace prefix imgeo

Stack Trace:
- ., 58/60
- ., 37/19
- ., 488/24
	at de.interactive_instruments.etf.bsxm.GmlGeoX.validate(GmlGeoX.java:322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Comment by thijsbrentjens** [comment]
@cportele good to know the test file is not the reason, so it seems an issue in the environment then.

**Comment by jonherrmann** [comment]
@thijsbrentjens can you please post the contents of
```
ls -l $ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/
ls -l $ETF_DIR"/td/bsx/lib
```

**Comment by thijsbrentjens** [comment]
ls -l /opt/etf-data2/ds/db/repo/de/interactive_instruments/etf/bsxm/
```
-rw-r--r-- 1 user user 34131660 May  4 15:29 etf-gmlgeox-1.0.2.jar
```
and:
ls -l /opt/etf-data2/td/bsx/lib/

```
-rw-r--r-- 1 user user   136369 May  2 16:19 aether-api-1.1.0.jar
-rw-r--r-- 1 user user    95536 Nov 25 17:17 apache-mime4j-core-0.7.2.jar
-rw-r--r-- 1 user user   421631 Nov 25 17:17 axiom-api-1.2.14.jar
-rw-r--r-- 1 user user   170746 Nov 25 17:17 axiom-impl-1.2.14.jar
-rw-r--r-- 1 user user  3022902 May  2 16:19 basex-7.9.jar
-rw-r--r-- 1 user user  3259402 Nov 25 15:21 bcprov-jdk15on-1.53.jar
-rw-r--r-- 1 user user  1416338 May  2 16:19 caffeine-2.0.1.jar
-rw-r--r-- 1 user user    41123 Nov 25 17:17 commons-cli-1.2.jar
-rw-r--r-- 1 user user   284184 Nov  3  2015 commons-codec-1.10.jar
-rw-r--r-- 1 user user   588337 May  2 16:19 commons-collections-3.2.2.jar
-rw-r--r-- 1 user user   160519 Nov 25 17:17 commons-dbcp-1.4.jar
-rw-r--r-- 1 user user   185140 Nov  3  2015 commons-io-2.4.jar
-rw-r--r-- 1 user user   208700 May  2 16:19 commons-io-2.5.jar
-rw-r--r-- 1 user user   434678 May  2 16:19 commons-lang3-3.4.jar
-rw-r--r-- 1 user user    62050 May  2 16:19 commons-logging-1.1.3.jar
-rw-r--r-- 1 user user   988514 Nov 25 17:15 commons-math-2.2.jar
-rw-r--r-- 1 user user   111119 Nov 25 17:17 commons-pool-1.6.jar
-rw-r--r-- 1 user user   116575 May  2 16:19 concurrentlinkedhashmap-lru-1.4.jar
drwxr-xr-x 3 user user     4096 May  4 14:04 de
-rw-r--r-- 1 user user    13356 Nov 25 17:17 deegree-core-annotations-3.3.17.jar
-rw-r--r-- 1 user user   468832 Nov 25 17:15 deegree-core-base-3.3.17.jar
-rw-r--r-- 1 user user   425094 Nov 25 17:17 deegree-core-commons-3.3.17.jar
-rw-r--r-- 1 user user   318081 Nov 25 17:15 deegree-core-coverage-3.3.17.jar
-rw-r--r-- 1 user user   753562 Nov 25 17:17 deegree-core-cs-3.3.17.jar
-rw-r--r-- 1 user user   265921 Nov 25 17:15 deegree-core-geometry-3.3.17.jar
-rw-r--r-- 1 user user  9074649 Nov 25 18:36 deegree-ogcschemas-20120804.jar
-rw-r--r-- 1 user user   313898 Nov  3  2015 dom4j-1.6.1.jar
-rw-r--r-- 1 user user  1346329 Nov 25 17:15 ehcache-core-2.6.5.jar
-rw-r--r-- 1 user user 34131660 May  4 15:36 etf-gmlgeox-1.0.2.jar
-rw-r--r-- 1 user user    15420 May  4 14:05 etf.log
-rw-r--r-- 1 user user   293863 Nov 25 17:17 FastInfoset-1.2.12.jar
-rw-r--r-- 1 user user    47465 Nov 25 17:17 geronimo-activation_1.1_spec-1.1.jar
-rw-r--r-- 1 user user   223298 Nov 25 17:17 geronimo-javamail_1.4_spec-1.7.1.jar
-rw-r--r-- 1 user user    28804 Nov 25 17:17 geronimo-stax-api_1.0_spec-1.0.1.jar
-rw-r--r-- 1 user user   189285 Nov 25 17:17 gson-2.2.2.jar
-rw-r--r-- 1 user user  1648200 Nov 25 17:17 guava-11.0.2.jar
-rw-r--r-- 1 user user   592008 May  2 16:19 httpclient-4.3.6.jar
-rw-r--r-- 1 user user   732765 Nov 25 15:21 httpclient-4.5.1.jar
-rw-r--r-- 1 user user   282793 May  2 16:19 httpcore-4.3.3.jar
-rw-r--r-- 1 user user   326594 Nov 25 15:21 httpcore-4.4.3.jar
-rw-r--r-- 1 user user   318052 Nov 25 18:36 imageio-ext-tiff-1.1.7.jar
-rw-r--r-- 1 user user    40659 Nov 25 18:36 imageio-ext-utilities-1.1.7.jar
-rw-r--r-- 1 user user   258160 Nov 25 18:36 jai-codec-1.1.3.jar
-rw-r--r-- 1 user user  1900631 Nov 25 18:36 jai-core-1.1.3.jar
-rw-r--r-- 1 user user  1140632 Nov 25 18:36 jai-imageio-1.1.3.jar
-rw-r--r-- 1 user user    38495 Nov 25 18:36 jai-mlibwrapper-1.1.3.jar
-rw-r--r-- 1 user user   125146 May  2 16:19 JavaEWAH-0.7.9.jar
-rw-r--r-- 1 user user   644148 Nov 25 17:17 javassist-3.12.1.GA.jar
-rw-r--r-- 1 user user   231882 Nov 25 15:21 jaxen-1.1.6.jar
-rw-r--r-- 1 user user   295355 Nov 25 15:21 jdom-2.0.2.jar
-rw-r--r-- 1 user user    12408 Nov 25 18:36 jgridshift-1.0-deegreeversion.jar
-rw-r--r-- 1 user user  1126403 Nov 25 18:36 jogl-1.1.2.jar
-rw-r--r-- 1 user user   280205 May  2 16:19 jsch-0.1.53.jar
-rw-r--r-- 1 user user    49672 Nov  3  2015 jsr173_api-1.0.jar
-rw-r--r-- 1 user user    33015 Nov 25 17:17 jsr305-1.3.9.jar
-rw-r--r-- 1 user user   794991 Nov 25 15:21 jts-1.13.jar
drwxr-xr-x 2 user user     4096 May  4 15:32 META-INF
-rw-r--r-- 1 user user   119180 Nov 28 10:49 mime-util-2.1.3.jar
drwxr-xr-x 3 user user     4096 May  4 14:04 nl
-rw-r--r-- 1 user user  2245410 May  2 16:19 org.eclipse.jgit-4.2.0.201601211800-r.jar
-rw-r--r-- 1 user user   102696 Nov 25 17:17 reflections-0.9.8.jar
-rw-r--r-- 1 user user  4677757 May  2 16:19 Saxon-HE-9.7.0-4.jar
-rw-r--r-- 1 user user   276420 Nov  3  2015 serializer-2.7.2.jar
-rw-r--r-- 1 user user   161867 Nov 25 15:21 stax2-api-3.1.4.jar
-rw-r--r-- 1 user user    23346 Nov  3  2015 stax-api-1.0-2.jar
-rw-r--r-- 1 user user   560997 May  2 16:19 tika-core-1.9.jar
-rw-r--r-- 1 user user    11794 Apr 29 15:02 validator-core-messages_en.properties
-rw-r--r-- 1 user user    13512 Apr 29 15:02 validator-core-messages_nl.properties
-rw-r--r-- 1 user user    13512 Apr 29 15:02 validator-core-messages.properties
-rw-r--r-- 1 user user   318956 Nov 25 18:36 vecmath-1.5.2.jar
-rw-r--r-- 1 user user   486013 Nov 25 15:21 woodstox-core-asl-4.4.1.jar
-rw-r--r-- 1 user user   487505 Nov 25 17:17 woodstox-core-lgpl-4.2.0.jar
-rw-r--r-- 1 user user  3154938 Nov  3  2015 xalan-2.7.2.jar
-rw-r--r-- 1 user user  1614683 May  2 16:19 xercesImpl-2.11.0.beta.jar
-rw-r--r-- 1 user user  1367760 Nov  3  2015 xercesImpl-2.11.0.jar
-rw-r--r-- 1 user user     7188 Nov 25 15:21 xmlpull-1.1.3.1.jar
-rw-r--r-- 1 user user  1126140 Nov 25 15:21 xmlsec-2.0.5.jar
-rw-r--r-- 1 user user    24956 Nov 25 15:21 xpp3_min-1.1.4c.jar
-rw-r--r-- 1 user user     5587 Nov 28 10:49 xqj2-0.2.0.jar
-rw-r--r-- 1 user user    16221 Nov 28 10:49 xqj-api-1.0.jar
-rw-r--r-- 1 user user   538830 Nov 25 15:21 xstream-1.4.8.jar
```

**Comment by jonherrmann** [comment]
Made a mistake in the posted commands:
The name must be always GmlGeoX.jar (case sensitive, its used by the BaseX class loader).

Please change the name in 
- "$ETF_DIR"/ds/db/repo/de/interactive_instruments/etf/bsxm/
- "$ETF_DIR"/td/bsx/lib

**Comment by thijsbrentjens** [comment]
@jonherrmann okay, but after doing this and restarting Tomcat, I still get the namespace issue.

**Comment by jonherrmann** [comment]
We checked a Windows and an OSX environment with exactly the same libraries and encounter different behaviors (same problem on OSX). We need to debug the code to understand the bug, @thijsbrentjens.

**Comment by jonherrmann** [comment]
Fixed in [Version 1.0.3](http://services.interactive-instruments.de/etfdev-af/release/de/interactive_instruments/etf/bsxm/etf-gmlgeox/1.0.3/etf-gmlgeox-1.0.3.jar)

@thijsbrentjens please download version 1.0.3 from here: http://services.interactive-instruments.de/etfdev-af/release/de/interactive_instruments/etf/bsxm/etf-gmlgeox/1.0.3/etf-gmlgeox-1.0.3.jar

**Comment by thijsbrentjens** [comment]
Thanks, just to be sure I re-installed the entire bsx driver and the gmlgeox libs. It seems to work on our environment.

I noticed that for some libs there are multiple versions in the bsx/lib directory now. Not sure if this could result in errors:

commons-io-2.4.jar
commons-io-2.5.jar

httpclient-4.3.6.jar
httpclient-4.5.1.jar

httpcore-4.3.3.jar
httpcore-4.4.3.jar

xercesImpl-2.11.0.beta.jar
xercesImpl-2.11.0.jar

**Comment by jonherrmann** [comment]
Good to hear.

I will check and update the dependencies. You can delete the commons-io-2.4.jar, httpclient-4.3.6.jar, httpcore-4.3.3.jar and xercesImpl-2.11.0.jar libraries in the lib folder.
