### ISSUE TITLE
Upload of XML file without XML prolog is not allowed

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-webapp#36]
### Description

From a user we got reports that their metadata documents can not be uploaded / used in the validator at: http://validatie.geostandaarden.nl/etf-webapp/testprojects?testdomain=Metadata

An example file is attached. [fabd3dfc-1436-4920-933f-924c1c3c1d2f.xml.txt](https://github.com/interactive-instruments/etf-webapp/files/331438/fabd3dfc-1436-4920-933f-924c1c3c1d2f.xml.txt)

My analysis: the XML prolog is missing in this document:

`<?xml version="1.0" encoding="UTF-8"?>`

The XML prolog is optional as far as I know, or am I wrong? In that case, the file should be processed. 

(Environment: CentOS, Java 8, Tomcat 8)

### Steps to Reproduce

1. got to http://validatie.geostandaarden.nl/etf-webapp/testprojects?testdomain=Metadata
2. Choose one of the validators
3. upload file
4. start test

**Expected behavior:** file is processed.

**Actual behavior:** Error message: `De geüploade file kan niet worden gebruikt: text/plainis not supported`

**Comment by thijsbrentjens** [comment]
Note that for uploading to GH I added the file-extension .txt, the orginal file is without this

**Comment by jonherrmann** [comment]
Yes, the prolog is optional. Will be fixed.

**Comment by thijsbrentjens** [comment]
Thanks :)

**Comment by jonherrmann** [comment]
Fixed in etf-webapp 1.0.9

**Comment by thijsbrentjens** [comment]
today I upgraded our test environment to etf-webapp 1.0.11.2, bsx driver to 1.0.5 and Soapui driver to 1.0.6. I used the artifacts from the repo at interactive instruments.

Uploading an XML file without the prolog is (still?) failing. The test environment is available here:

Steps:
1. go to http://test.validatie.geostandaarden.nl/etf-webapp/testprojects?testdomain=Metadata
2. choose one of the test projects in Metadata
3. upload the file (attached in this issue before)
4. start test

**Comment by jonherrmann** [comment]
Please check and update your [build.gradle](https://github.com/Geonovum/etf-webapp/blob/master/build.gradle#L47). The issue has been fixed in the [ii-commons-util library 1.2.9](https://github.com/interactive-instruments/etf-webapp/blob/master/build.gradle#L51).

**Comment by jonherrmann** [comment]
No issues with the 1.2.9 version from the _etf-public-releases_ and the _release_ repo

**Comment by thijsbrentjens** [comment]
I deployed the etf-webapp from the etf-public-releases repo. In the WEB-INF/lib dir this jar is deployed: ii-commons-util-1.2.9.jar

I only (manually) added some CSS this time, didn't deploy a custom build.

I restarted Tomcat (several times). So what could be going on?

**Comment by jonherrmann** [comment]
Mmh good question - I will check again, with a fresh deployment!
