### ISSUE TITLE
Gradle build / compilation fails on xercesImpl:2.11.0.beta dependency

### ISSUE THREAD

**Issue by thijsbrentjens** [interactive-instruments/etf-webapp#49]
Building the etf-webapp war-file (after resolution of #36)  fails. I get a compilation error:

```
./gradlew build war
ETF-BDA: Applying ii BDA gradle script 1.0.23 to the project
ETF-BDA: Authenticating will be done as user t.brentjens@geonovum.nl
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find xercesImpl.jar (xerces:xercesImpl:2.11.0.beta).
  Searched in the following locations:
      http://services.interactive-instruments.de/etfdev-af/ext-releases-local/xerces/xercesImpl/2.11.0.beta/xercesImpl-2.11.0.beta.jar
```

I checked and the manual download fails too. Is the jar-file corrupt or not accessible?

### Operating systems and browser
- Linux (Ubuntu 16.04 based)
- JDK 1.8.0_91 (OpenJDK), 64 bit

### Steps to Reproduce
1. go to the root dir of the src code
2. execute the command: ``` ./gradlew build war ```

The build fails with the above message.

**Comment by jonherrmann** [comment]
Fixed an internal network issue which caused problems with the artifactory service.

**Comment by thijsbrentjens** [comment]
Build successful :+1:
