### ISSUE TITLE
Test Reports: central CSS fallback address in reports

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-webapp#65]
Shared Reports are not styled if the etf service is not running.The report should embed a fallback logic for loading centrally available CSS. To ensure a consistent styling of "older" reports we should use a versioning schema in the URLs.

**Comment by jonherrmann** [comment]
@cportele 

Where should the CSS be deployed? Should we use and link to a free CDN (cloudflare, etc.)  first and then use ii services as fallback?

**Comment by cportele** [comment]
@jonherrmann 

The approach sounds good.
