### ISSUE TITLE
Support for legal notice, disclaimers etc.

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/etf-webapp#7]
Often it will be necessary to include a legal notice, information about data privacy or other disclaimers on each page of the web application, typically via links in the footer.

**Comment by jonherrmann** [comment]
Blocks #19

**Comment by jonherrmann** [comment]
Need feedback which information should be included. Not clear to me if we should additionally add  ServiceIdentification and ServiceProvider information based on OWS.
