### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/etf-webapp#71]
The online documentation for both workflows need to be updated.

Most important:
- [x] Simple workflow, English

Less important:
- Regular workflow, Deutsch
- Simple workflow, English
- Regular workflow, Deutsch

**Comment by jensscheerlinck** [comment]
Went over the user manual after installing the etf-webapp on a Linux machine.
Minor edits suggested in #104

**Comment by cportele** [comment]
The regular workflow and the German versions have been moved to a separate issue: #106
