### ISSUE TITLE
Update documentation for administrators deploying ETF

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/etf-webapp#72]

**Comment by jensscheerlinck** [comment]
http://docs.etf-validator.net/Admin_manuals/index.html#_install_etf_web_application_on_linux

Step 1. Download the latest ETF-Webapp version, using etf-public-dev as user and password.
-> link provided resolves to a 404 page not found.

(http://docs.etf-validator.net/Admin_manuals/:https://services.interactive-instruments.de/etfdev-af/etf-public-dev/de/interactive_instruments/etf/etf-webapp/2.0.0/etf-webapp-2.0.0.war)

**Comment by jonherrmann** [comment]
Fixed the link -thanks Jens!
