### ISSUE TITLE
More information should be shown in the "simplified" view in a Test Report

### ISSUE THREAD

**Issue by cportele** [interactive-instruments/etf-webapp#79]
Including the version of the ETS in the Test Report was a requirement. Currently, the version is only shown in the "all details" view, but it should be shown always to properly meet the requirement.

Showing the time stamp was a requriement, too. Currently, it is only shown in the "less information" view, but it should be shown in the "simplified" view, too.

**Comment by cportele** [comment]
The version of the ETS should also be shown in the ETS details in the "Start test" tab - in addition to the description, tags and applicable test object types.

**Comment by jonherrmann** [comment]
It is another module and I added a new issue for it
