### ISSUE TITLE
Constraints test does not capture error in Conformance class: Application Schema, Protected Sites simple

### ISSUE THREAD

**Issue by sMorrone** [interactive-instruments/etf-webapp#86]
I validated an example file containing the erroneus designation value “http://inspire.ec.europa.eu/codelist/IUCNDesignationValue/wildernessAreaFakeValue” for a  PS with  designationScheme=”http://inspire.ec.europa.eu/codelist/DesignationSchemeValue/IUCN" and  it passes validation (relevant log at http://35.157.17.37/etf-webapp/v2/TestResults/d69a2d0e-10e8-4d6c-8060-d522ace5eb51/log).
Would you please check?
Stefania

**Comment by jonherrmann** [comment]
Moved it to the INSPIRE Executable Test Suite repository
https://github.com/inspire-eu-validation/ets-repository/issues/44

Best regards
Jon
